image: node:latest
stages:
  - build
  - deploy
  - deploy-dev

build:
  stage: build
  before_script:
    - apt-get update -y 
    - apt-get install -y zip 
  script:
    - yarn install
    - CI=false yarn run build
    - cd build 
    - zip -r ../public.zip * 
  artifacts:
    paths:
      - public.zip

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - curl -X POST -u '$dns-web':$dnswebpassword --data-binary "@public.zip" https://dns-web.scm.azurewebsites.net/api/zipdeploy
  only:
    - master

deploy-dev:
  stage: deploy-dev
  dependencies:
    - build
  script:
    - curl -X POST -u '$dns-web-dev':$dnswebdevpassword --data-binary "@public.zip" https://dns-web-dev.scm.azurewebsites.net/api/zipdeploy
  only:
    - develop